services:
  # FastAPI Backend Service
  - type: web
    name: website-api
    env: python
    region: oregon
    plan: free
    buildCommand: "pip install poetry && poetry config virtualenvs.create false && poetry install"
    startCommand: "poetry run python backend/api.py"
    envVars:
      - key: PYTHON_VERSION
        value: "3.11.0"
      - key: PORT
        value: "8000"
    healthCheckPath: /

  # Dash Frontend Service  
  - type: web
    name: website-frontend
    env: python
    region: oregon
    plan: free
    buildCommand: "pip install poetry && poetry config virtualenvs.create false && poetry install"
    startCommand: "poetry run python frontend/app.py"
    envVars:
      - key: PYTHON_VERSION
        value: "3.11.0"
      - key: PORT
        value: "8050"
      - key: API_BASE_URL
        value: "https://api.gitthub.org"